name: snowflake-deploy

#Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths:
      - 'EMP/PRIVATE/**'
      
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange

          echo "Step 2: Running schemachange"
          schemachange \
            --file-path "$GITHUB_WORKSPACE/EMP/PRIVATE" \
            --snowflake-account "$SF_ACCOUNT" \
            --snowflake-user "$SF_USERNAME" \
            --snowflake-password "$SF_PASSWORD" \
            --snowflake-role "$SF_ROLE" \
            --snowflake-warehouse "$SF_WAREHOUSE" \
            --snowflake-database "$SF_DATABASE" \
            --snowflake-schema "SCHEMACHANGE" \
            --change-history-table "$SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY" \
            --create-change-history-table
